# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49cc188d82b5d165cd10c39a57d5319f07d8c0c698d30644c53aacf0d0690a30eb2a777af650a97e4249e00e26effa317b64fd57b1630389a2fd5451e9f02a3a

test:
  secret_key_base: abe8012bbe2d7890e7b956c0d3d6929ed026f4362e5a215b370c543e59334708571738d872210be4bc6293fda9737b623e72906dbfb89752559d9f82d961cc8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
   secret_key_base: 49cc188d82b5d165cd10c39a57d5319f07d8c0c698d30644c53aacf0d0690a30eb2a777af650a97e4249e00e26effa317b64fd57b1630389a2fd5451e9f02a3a
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
